// Code generated by goctl. DO NOT EDIT.
// Source: selectrpc.proto

package server

import (
	"context"

	"bgp-zero/tableselect/selectrpc/internal/logic"
	"bgp-zero/tableselect/selectrpc/internal/svc"
	"bgp-zero/tableselect/selectrpc/selectrpc"
)

type SelectrpcServer struct {
	svcCtx *svc.ServiceContext
	selectrpc.UnimplementedSelectrpcServer
}

func NewSelectrpcServer(svcCtx *svc.ServiceContext) *SelectrpcServer {
	return &SelectrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *SelectrpcServer) Ping(ctx context.Context, in *selectrpc.Request) (*selectrpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
