// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: testuser/rpc/user.proto

package testuser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Usrt_GetUser_FullMethodName = "/testuser.usrt/getUser"
)

// UsrtClient is the client API for Usrt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsrtClient interface {
	GetUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type usrtClient struct {
	cc grpc.ClientConnInterface
}

func NewUsrtClient(cc grpc.ClientConnInterface) UsrtClient {
	return &usrtClient{cc}
}

func (c *usrtClient) GetUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, Usrt_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsrtServer is the server API for Usrt service.
// All implementations must embed UnimplementedUsrtServer
// for forward compatibility
type UsrtServer interface {
	GetUser(context.Context, *IdRequest) (*UserResponse, error)
	mustEmbedUnimplementedUsrtServer()
}

// UnimplementedUsrtServer must be embedded to have forward compatible implementations.
type UnimplementedUsrtServer struct {
}

func (UnimplementedUsrtServer) GetUser(context.Context, *IdRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUsrtServer) mustEmbedUnimplementedUsrtServer() {}

// UnsafeUsrtServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsrtServer will
// result in compilation errors.
type UnsafeUsrtServer interface {
	mustEmbedUnimplementedUsrtServer()
}

func RegisterUsrtServer(s grpc.ServiceRegistrar, srv UsrtServer) {
	s.RegisterService(&Usrt_ServiceDesc, srv)
}

func _Usrt_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsrtServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usrt_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsrtServer).GetUser(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Usrt_ServiceDesc is the grpc.ServiceDesc for Usrt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Usrt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "testuser.usrt",
	HandlerType: (*UsrtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getUser",
			Handler:    _Usrt_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testuser/rpc/user.proto",
}
