// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"bgp-zero/testuser/rpc/internal/logic"
	"bgp-zero/testuser/rpc/internal/svc"
	"bgp-zero/testuser/rpc/types/testuser"
)

type UsrtServer struct {
	svcCtx *svc.ServiceContext
	testuser.UnimplementedUsrtServer
}

func NewUsrtServer(svcCtx *svc.ServiceContext) *UsrtServer {
	return &UsrtServer{
		svcCtx: svcCtx,
	}
}

func (s *UsrtServer) GetUser(ctx context.Context, in *testuser.IdRequest) (*testuser.UserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
