// Code generated by goctl. DO NOT EDIT.
// Source: selectrpc.proto

package selectrpcclient

import (
	"context"

	"bgp-zero/tableselect/selectrpc/selectrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = selectrpc.Request
	Response = selectrpc.Response

	Selectrpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultSelectrpc struct {
		cli zrpc.Client
	}
)

func NewSelectrpc(cli zrpc.Client) Selectrpc {
	return &defaultSelectrpc{
		cli: cli,
	}
}

func (m *defaultSelectrpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := selectrpc.NewSelectrpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
