// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package usrt

import (
	"context"

	"bgp-zero/testuser/rpc/types/testuser"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IdRequest    = testuser.IdRequest
	UserResponse = testuser.UserResponse

	Usrt interface {
		GetUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserResponse, error)
	}

	defaultUsrt struct {
		cli zrpc.Client
	}
)

func NewUsrt(cli zrpc.Client) Usrt {
	return &defaultUsrt{
		cli: cli,
	}
}

func (m *defaultUsrt) GetUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	client := testuser.NewUsrtClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}
